### PR TITLE
Development

### PR DESCRIPTION
**Pull request by selul**

### CODE REVIEW

**Comment by irinelenache** [comment]
@selul Tested it and some issues that were fixed seem to happen again:

- #475 
- for #377 i get this error again https://github.com/Codeinwp/feedzy-rss-feeds/pull/510#issuecomment-801031308
- #480 doesn't work fine in google chrome responsive mode and with an Android phone on browserstack (with iPhone it seems to work fine)

**Comment by irinelenache** [comment]
@girishkrishaweb @selul everything seems to work fine except the PHP notice with this feed https://defend.wikileaks.org/feed/ and latest versions of PHP and WP

**Comment by girishkrishaweb** [comment]
@irinelenache Added a new patch to solve the PHP notice issue.

**Comment by irinelenache** [comment]
@girishkrishaweb the PHP notice still appears **everytime i import the feed** and sometimes when i click **Save & activate**

**Comment by girishkrishaweb** [comment]
@irinelenache `WP HTTP Error: cURL error 7: Failed to connect to defend.wikileaks.org port 443: Connection timed out` I'm getting timeout issue from the feed host. This happens sometimes only. and this happens only with this URL. You can try to test different URLs. If you would like to solve PHP warning with the same feed hosting then we need to add more header timeout.

**Comment by girishkrishaweb** [comment]
@irinelenache Can I have a screenshot or video demo for it?

**Comment by girishkrishaweb** [comment]
@irinelenache I added a new patch. Please check with it.

**Comment by irinelenache** [comment]
@girishkrishaweb now it works fine, didn't get any notice in the log 👍

**Pull request merged**
