### PR TITLE
Allow target attribute in escaping html

### LINKED ISSUE #621: Read More using [#item_url] should be opening a link in a new tab
### Description:
Based on my findings and understanding it's a minor bug but I might be missing something in the code.
So, if the user wants to have a Read More button somewhere in the content that opens the URL of the source they can add **[#item_url]** magic tag like this:
https://vertis.d.pr/ohql9h

In my opinion, the default behavior should be to open a link in a new tab and if I check the code of the plugin this is what it suppose to be doing:
https://github.com/Codeinwp/feedzy-rss-feeds/blob/master/includes/admin/feedzy-rss-feeds-import.php#L1327

However, when the post is imported that **target="_blank">** is missing:
https://vertis.d.pr/Mxi0O2

Am I checking the incorrect line of the code or why is it missing?

### How to reproduce:
1. Create a new import with any feed.
2. Try to use [#item_url] in the content
3. Check the front-end whether a link opens in a new tab or the same tab.

### Expected behaviour:
Read More button should be opening the original item in a new tab.

### Current behaviour:
Read more button opens the original item in the same tab.

### Reference:
Provided above.
Potential client asked here - https://secure.helpscout.net/conversation/1699828679/299810?folderId=212385

### Technical info
* WordPress version: 5.8.2
* Plugin version: 3.8.0

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #621

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the issue is fixed. Can we inform the user somehow that the link will open in a new tab? (For accessibility reasons)

**Comment by girishpanchal30** [comment]
@irinelenache Yes I can, but in widget and Gutenberg block, we have helper text over there. For shortcode, Can we describe in plugin documentation? Or could you let me know where we need to add information for the same?

**Comment by irinelenache** [comment]
@girishpanchal30 I'm talking about [this link](https://vertis.d.pr/kHs2CF). 
Maybe it can use an icon like this or something similar

image

**Comment by girishpanchal30** [comment]
@irinelenache  Added external link icon, can you re-test?

**Comment by irinelenache** [comment]
@girishpanchal30 I can't see the icon in frontend. You can check on this instance:
```
 Admin area URL: https://rottenfather.tastewp.com/wp-admin 
 Username: irinel 
 Password: Rq-znW77-3s 
```

**Comment by girishpanchal30** [comment]
> @girishpanchal30 I can't see the icon in frontend. You can check on this instance:
> 
> ```
>  Admin area URL: https://rottenfather.tastewp.com/wp-admin 
>  Username: irinel 
>  Password: Rq-znW77-3s 
> ```

@irinelenache Fixed icon style issue, can you re-test again?

**Comment by irinelenache** [comment]
@girishpanchal30 Now the icon is visible, thanks 👍

**Pull request merged**
