### PR TITLE
Display source name when author unavailable

### LINKED ISSUE #543: Source doesn't show in feed
### Description:
Source doesn't show in feed

### How to reproduce:
1. Enter multiple feeds
2. Enable showing sources, by putting "source" into the Item Options field labeled "When using multiple sources, should we display additional meta fields? - source (comma-separated list)."
3. The source doesn't show?

### Expected behavior:
The source of the RSS feed should show.

### Current behavior:
It doesn't show any source.

### Reference:
Here is one of the feeds where the issue can be seen:
https://accelermedia.com/sites/

### Technical info
* WordPress version: 5.7.1
* Plugin version: 3.6.4

### PR DESCRIPTION
**Pull request by girishkrishaweb**
Close #543

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishkrishaweb i used two feeds, mentioned in the issue ( http://feeds.ign.com/ign/games-all, https://www.nintendolife.com/feeds/latest ) and inputed **source** for **Additional meta fields**. For the items that don't have an author, the source isn't displayed https://prnt.sc/12wwcdi

**Comment by girishkrishaweb** [comment]
@irinelenache Have you selected source in Gutenberg block settings 
block-setting-soruce
?

After selecting this, you will get a source name like this 
feed-import-view-source

Basically, we have implemented like if an author is not in the feed and have selected source from gutenberg block setting.

Would you like to implement the same things without selecting a source from the gutenberg block settings?

**Comment by irinelenache** [comment]
@girishkrishaweb I tried again, maybe i didn't have the updated zip. Now if i use both the mentioned feeds, i get an error for one of them, even if it's valid https://prnt.sc/12x7dmc . For the source name, i see that it works only on front-end, in editor it isn't displayed https://prnt.sc/12x8i62

**Comment by girishkrishaweb** [comment]
@irinelenache Can you re-check the issue? I have created new patch.

**Comment by irinelenache** [comment]
@girishkrishaweb Now the source is displayed both in editor and frontend 👍 
As i said, this feed http://feeds.ign.com/ign/games-all gives this error https://prnt.sc/12x7dmc when it's used with another feed, if i use it alone it works fine. Is this expected? If it's expected, this can be merged.

**Comment by girishkrishaweb** [comment]
@irinelenache  Can i have both the feed URL? So we can test same on our end.

**Comment by irinelenache** [comment]
@girishkrishaweb   sure, http://feeds.ign.com/ign/games-all https://www.nintendolife.com/feeds/latest

**Comment by girishkrishaweb** [comment]
@irinelenache We have checked with the above URLs and it seems like working without any issue. https://www.loom.com/share/ea4a11857f744177abfe4cd31f8658b0

**Comment by irinelenache** [comment]
@girishkrishaweb thanks for pointing it out with the video, i took a different approach:
https://www.loom.com/share/a5ea9419a03b46cba4e5adc7bb5c3d86

**Comment by girishkrishaweb** [comment]
@irinelenache We have checked with your approach but we haven't found any issue https://www.loom.com/share/dae7eb1dfd4e49c988de939ec5327a42. Are you able to access the feed URL? Just want to verify network blocking.

**Comment by irinelenache** [comment]
@girishkrishaweb i'm ablee to access the URL, i don't know why the problem is present only for me. 
This is the instance where i'm testing:
```
https://revolutionary-bengal.jurassic.ninja
user: demo
password:  Ev8svcoQsOze
```

**Comment by girishkrishaweb** [comment]
@irinelenache Can you please try this with http://feeds.ign.com/ign/games-all?format=xml  I think PHP-XML extension is not enabled on server/hosting

**Comment by irinelenache** [comment]
@girishkrishaweb it works fine with the link you provided, thanks 👍

**Pull request merged**
