### PR TITLE
Add modify links action

### PR DESCRIPTION
**Pull request by girishpanchal30**
### Summary

In this PR, I've added modify links action to modify the `<a></a>` HTML attributes.

### Screenshots 

With Pro Version:
https://tinyurl.com/2ypn2944
https://tinyurl.com/23qrd67z

Without Pro version:
https://tinyurl.com/27xpoqg2
https://tinyurl.com/2b3gelle

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/647

### CODE REVIEW

**Review by Soare-Robert-Daniel — APPROVED** [review]

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30, thank you for taking care!

Here are my findings:
- there are some weird characters appearing for certain parts of the content (those were not links before)
image

- the panel doesn't have the same structure as in your screenshot:
image

- I set the links to open in the same tab and be nofollow, but this is not respected on the frontend:

image
image


live behavior:
https://overdodevelopment.s1-tastewp.com/2024/08/30/8-mistakes-i-made-when-building-my-first-wordpress-plugin-using-ai-with-no-prior-development-experience/

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina

> there are some weird characters appearing for certain parts of the content (those were not links before)

Can you please share Feed URL?

> the panel doesn't have the same structure as in your screenshot:

It could be a cache issue on your end; everything looks fine from my side.
Ref: https://tinyurl.com/25lj2l7p

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 here is the feed: https://wpshout.com/feed

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina I've fixed the mentioned issue with the latest commit.

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 I am not sure why, but when using the Modify links action, the import no longer works:

image

Instance:

- test
- MrAP6PU)D@%jrDMD3qrTO#em
- https://groovyfriends.s2-tastewp.com/wp-admin/users.php?id=2

Also, from the previous comment (just making sure), have you checked this too?

> I set the links to open in the same tab and be nofollow, but this is not respected on the frontend:

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina It seems issue with PHP 8, now it fixed with the latest commit.

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30, great! It works as expected now. Thank you!

**Pull request merged**
