### PR TITLE
New UI design implementation

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close Codeinwp/feedzy-rss-feeds-pro#405

### CODE REVIEW

**Comment by mghenciu** [comment]
### Note: this is a work in progress review, so I'll be adding them while testing.
Great work overall @girishpanchal30 🚀 
Here are some things I noticed so far:
___
### Visual - for the whole UI in the Dasboard
- [ ] please change the Font Family. The font family should [be a System font ](https://css-tricks.com/snippets/css/system-font-stack/#aa-method-1-system-fonts-at-the-element-level). So in the end it would be something like `font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif`. Wordpress uses the same approach for their UI:
Screenshot 2022-04-26 at 17 45 37

- [ ] This one it's on me, as I didn't applied it in Figma, only mentioned the CSS there -> please add a **Hover State for all Secondary buttons** . So on Hover the secondary buttons should have `box-shadow: inset 0 0 0 1px #4268cf, inset 0 0 0 2px #f7f9fd;` and background on hover should be #F7F9FD.
Here's a preview to see the difference with Default & Hover states:
image


___
### Accessibility 

- [ ] **Focus State**. I noticed that **the focus state is missing** on the Support Page, for both links & Buttons. From an Accessibility point of view, this is quite important - so we need to add it everywhere (in Feedzy UI).
Here we'll also use the default WP core style, on focus: `box-shadow: 0 0 0 1px #fff, 0 0 0 3px #2271b1;`
Screenshot 2022-04-27 at 13 05 44

Same thing for other Interactive Elements on the page, such as links, tabs and so on. Those **need to have a** [focus state](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html), as recommended by accessibility guidelines because not everyone is using a 'conventional' keyboard + mouse setup. 
For example here I am focusing on the Docs Tab, but I can't visually see this:
Screenshot 2022-04-27 at 13 09 28

You can try using the Feedzy interface just with a keyboard (no mouse) - using the Tab key, to get a better idea why this is important. 



___
### Support- Getting Started tab

- [ ] in Keyword Filtering card, the button link goes to [Feedzy Page](https://themeisle.com/plugins/feedzy-rss-feeds/#reasons). Let's [change it to this](https://docs.themeisle.com/article/1154-how-to-use-feed-to-post-feature-in-feedzy#filters), which refers to Filtering.

___
### Support - Documentation tab

- [ ] the **In Feedzy how do I...** card, leads to [this page](https://docs.themeisle.com/article/540-what-actions-and-filters-are-available-in-feedzy) now, but I think it should be [this one](https://docs.themeisle.com/article/942-in-feedzy-how-do-i).
- [ ] On the **Need help with Feedzy?** card, the Support Forum button should take users to the [WP forum](https://wordpress.org/support/plugin/feedzy-rss-feeds/). While the blue link (as seen in Figma), should take users to the [contact page](https://themeisle.com/contact/), from where they can login and create a support issue:
Screenshot 2022-04-26 at 18 07 44

___
### Support - Feedzy Pro tab
@selul , on this tab for the **View all Feedzy Pro features** button, now it goes to the [Feedzy Docs page](https://docs.themeisle.com/article/1119-feedzy-rss-feeds-documentation), as there is no Upgrade page for Feedzy.
Do you think maybe we should change the link to [the main page](https://themeisle.com/plugins/feedzy-rss-feeds/#features) ? instead of using the Docs link.

Screenshot 2022-04-27 at 14 06 53

___
### Optional things

- [ ] **Tab Behaviour**. This is related to how Tabs look on Mobile. I think it may make more sense to use the same approach as Neve's. Here's how it looks now on Mobile in **Feedzy** (scroll Behaviour):
image


and this is how **Neve** tab works:
image
 
There also look to be some **Overlay Issues** with the wpadminbar.

___
Another thing here, also related to Tabs - is the **Transition between Tabs**. In Feedzy when switching tabs the page will reload, while in Neve - this looks to be happening in the same view. Not a big issue, more like a question; and maybe this is related to the fact that Neve UI is made in React:

https://user-images.githubusercontent.com/52494172/165512494-0643c8bc-0037-4a7a-a1c3-b804414c605f.mov



___
- [ ] on the Feedzy Pro & Help us improve tabs, I would hide the **Need help with Feedzy?** card - as we want the focus to be on the **See Pro features** button and the **Take the Survey** button

___
- [ ] Ideally, the section title should be reactive - meaning that it should have the name of the selected Tab. So for example in this case it should be Documentation. Right now it's Getting Started all the time:
Screenshot 2022-04-27 at 14 28 30

**Comment by selul** [comment]
> on this tab for the View all Feedzy Pro features button, now it goes to the [Feedzy Docs page](https://docs.themeisle.com/article/1119-feedzy-rss-feeds-documentation), as there is no Upgrade page for Feedzy.
Yes, let's use the pricing page https://themeisle.com/plugins/feedzy-rss-feeds/#pricing

**Comment by mghenciu** [comment]
- [ ] There may be an issue with the Adding Category page, as I don't see the Publish Panels.
**Old** UI:
Screenshot 2022-04-28 at 20 43 42

___
**New** UI:
Screenshot 2022-04-28 at 20 43 55


___
### General UX and quality of life things that can be addressed later:

### Settings Tab - but it's a general rule

- [ ] **View Exit Confirmation**. As mentioned before, right now when changing Tabs - the page view refreshes, which means that if a user writes something without saving, and then changes the Tab -> the changes won't be saved. And we don't have any notice for this, which also happens if a users leaves Feedzy page (for example goes WP Appearance Tab) - the changes won't be save. So it would help at some point to have this notice when an user leaves the Tab/Page - without saving it:
image
This is a common UX pattern, to confirm with users that it's ok to discard their unsaved changes.

___

- [ ] **Help Button links**. The purpose of the Help Button in this type of view, is to act as shortcut to the docs for that feature. So for example if I as an user, I am on the Proxy Tab and I don't understand how that features works -> I would click on the Need help button, which will take mere on a doc about [Proxy](https://docs.themeisle.com/article/714-how-to-use-proxy-settings-in-feezy). And same thing for other features Tabs like WordAi, etc.
Screenshot 2022-04-28 at 18 47 29

___

- [ ] **Doc link on the Miscellaneous tab**. The link here leads to General Docs. If we use the approach with the Help Button, mentioned above - then it's fine. Otherwise, it should [go here](https://docs.themeisle.com/article/841-how-to-add-canonical-tags-for-imported-posts.
)
Screenshot 2022-04-28 at 18 53 52

___

- [ ] **Add Category docs**. At some point it would be nice to have some kind of **Help button** for the Add Category page. The link [should go here](https://docs.themeisle.com/article/1119-feedzy-rss-feeds-documentation#categories).
And it can look like this ([Figma](https://www.figma.com/file/vJ62MRf3FgOBd1i8WWJeIv/Feedzy?node-id=648%3A2811)):
Screenshot 2022-04-28 at 19 08 10

___

### New Import Page

**Other plugins & the Main Container**. Not sure if this is a bug from how the other plugins work or is just normal.
But when I've installed [All in One Seo](https://wordpress.org/plugins/all-in-one-seo-pack/) plugin,  and when I tried to import a new feed - > their UI appears inside Feedzy container, and it's quite big. Normally I think it should appear at the end of the Page. So at some point I would check if we could make the Main container in a way, that other plugins don't break it.
image
Screenshot 2022-04-28 at 19 32 31

___

- [ ] The Add a Category button from here, should open in a New Tab - or at least show the **Exit Confirmation** (mentioned above). Because right now it opens in the same tab, which means that all the unsaved changes in the page will be lost.
Screenshot 2022-04-28 at 20 39 41


____

- [ ] **Closing Dropdowns**. Drop downs in general, should close on Click Outside. Meaning that if as an user I use the Insert Tag button and the Drop down becomes open, it should close itself after I click outside it. Right now it closes only after a Magic Tag is inserted. Using this approach we'll also make sure there are no cases when a bunch os drop-downs are opened, and need to be closed manually:

https://user-images.githubusercontent.com/52494172/165817020-20129b88-5381-410b-95ed-ad266cb7d249.mov


___

- [ ] **Pro Options in Drop-downs**. As I already mentioned before, we'll try to show as much as possible the Pro features/options in the Free builds. This thing also applies for the Drop-downs. Here's an example from another product we have in our portfolio, where the Pro Drop-downs are also visible:
image

Now in Feedzy case I think we do this, what I would improve - is **making sure it's clear for users that those options are Disabled in Free, but available in Pro**. So it could be something like this (I've added opacity 0.6 for disabled items; and the **Pro** word):
Screenshot 2022-04-28 at 21 13 52


___
- [ ] Auto Delete section has the Pro Blur effect, but the label doesn't have the Pro Badge:
image
image

**Comment by mghenciu** [comment]
### Elementor Widget
Everything looks good here. 
The only things I would improve is the **Hover State for Pro items, when those are locked** - besides the locked state and the not-allowed cursor, I think we can use this one message on hover (with the `title` html tag: _Unlock this feature with) Feedzy Pro_.

And it will look something like this:
Screenshot 2022-04-28 at 21 28 59

___

- [ ] And for the **Feed Layout**, the bg-color of the box, I think are a bit different right now.
Screenshot 2022-04-28 at 21 36 56


It should be like this on **Dark Mode**:
image

#64666A for the Selected Box
#34383C - unselected Box

And the light Mode colors are in Figma:https://www.figma.com/file/vJ62MRf3FgOBd1i8WWJeIv/Feedzy?node-id=582%3A1539


____
### For the Gutenberg widget I am not sure if there are any changes implemented - so I didn't tested.

That's all for now.
Thank you again for the hard work, @girishpanchal30 . Really nice job, overall 🚀

**Comment by girishpanchal30** [comment]
@mghenciu Fixed above mentioned issue, please reverify

>And for the Feed Layout, the bg-color of the box, I think are a bit different right now.
I can't replicate this issue in my local, Can you share how I can fetch this issue?

For my end, it looks like this: https://www.awesomescreenshot.com/image/26450172?key=4b753b9613c9ee4ff3785d31be430048

Thanks

**Comment by mghenciu** [comment]
> Can you share how I can fetch this issue?

@girishpanchal30 , I think it's related to how the **Dark/Light mode preferences in Elementor** work.
So the issue I was referring happens when the UI theme is set to **Auto detect**.
Screenshot 2022-04-29 at 13 58 36


May be related to [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)
___
When either the Dark or Light mode are selected (and not auto), then it works as expected:
Screenshot 2022-04-29 at 14 01 21


Note that I've tested on 2 devices (macOS, Chrome), and same thing happens.

**Comment by girishpanchal30** [comment]
@mghenciu Fixed the Dark/Light mode theme issue, Please check and do let me know if you have an issue.

Thanks

**Comment by girishpanchal30** [comment]
@irinelenache Fixed all above issue, Please retest with latest commit.

> In the Content field the default tag doesn't look like the others added and also when i manually type tags they don't appear like the ones added from dropdown (for other fields, i saw the style of the tag is changed after pressing enter)

tagify JS mixed content field is not auto converting to tags when the user presses the enter button. because the mixed content field type is textarea so we should use the shortcode from drop-down

I hope you understand.

cc @selul
Thanks

**Comment by selul** [comment]
>  because the mixed content field type is textarea so we should use the shortcode from drop-down
Looks ok.

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and most of the issues are fixed 🚀 

About this one:

> When adding the import source, if i first add a link and try to add a category after, only the category will remain added (it works fine in reverse order). Also, if i have a category and some links added, deleting the category will delete all items https://vertis.d.pr/kyRabt

Here is how it works now:
✅  I can add multiple links to an import
❌ I can't add both links and categories to the same import
❌ I can't add more than one category to the same import

@selul Is this the expected behaviour of the plugin?

If this is expected, i think we can proceed and merge this 🚀

**Comment by selul** [comment]
@irinelenache no is not, it should work as before. @girishpanchal30 can we fix it?

**Comment by girishpanchal30** [comment]
@irinelenache Fixed the above mentioned issue, Please retest with the latest commit.

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and now all issues are fixed, thank you 🚀

**Pull request merged**
