### PR TITLE
Fix PHP extension warnings while loading or importing feed

### PR DESCRIPTION
**Pull request by girishkrishaweb**
PHP extension - mbstring and iconv warnings
Issues - https://github.com/Codeinwp/feedzy-rss-feeds/issues/252 & https://github.com/Codeinwp/feedzy-rss-feeds/issues/377

### CODE REVIEW

**Comment by tudor-themeisle** [comment]
Tested with: 

- wp 5.7
- php 8

No similar error in the log for (#252);  

For #377, I get a similar error, mine is ( [17-Mar-2021 11:58:31 UTC] PHP Notice: https://defend.wikileaks.org/feed/ is invalid XML, likely due to invalid characters. XML error: Mismatched tag at line 6, column 8 in .../wp-includes/class-simplepie.php on line 1543 )

**Comment by irinelenache** [comment]
@girishkrishaweb i get the same error as @tudor-themeisle with the wikileaks feed

**Comment by girishkrishaweb** [comment]
@irinelenache I have checked this issue and I got the validation error when I save the feed. 
Tested with
- WP 5.7 
- PHP 8.0

It is possible for you to share a video demo with me?

**Comment by irinelenache** [comment]
@girishkrishaweb which PR did you use for testing?

- With this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/510 the posts were imported and i got the mentioned notice in the debug.log

- With this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/508 the posts were imported and i didn't get any error in the debug.log

**Comment by girishkrishaweb** [comment]
@irinelenache I used PR #508 to test it. We had an issue with PR #510 (CI failed) so we created a common branch to push all the changes.

**Pull request closed without merging**
