### PR TITLE
Release

### PR DESCRIPTION
**Pull request by vytisbulkevicius**
### **New Features**

- **Paraphrasing using OpenAI / Chat GPT [PRO]:** This feature enables users to utilize OpenAI's Chat GPT for paraphrasing text. It can assist in rephrasing and generating alternative wording for content.
- **Content summarization support using OpenAI / Chat GPT  [PRO]:** With this feature, users can access support for summarizing longer pieces of content, making it easier to condense and understand the main points of a text.
- **Added support to create a dynamic category [PRO]:** Feedzy can now create WordPress categories automatically during the import by taking the category name from the RSS XML Feed.
- **Added individual fallback image setting [PRO]:** This feature allows users to set specific backup images for individual import jobs, not only a general fallback image for all import jobs.
- **Ability to trim content to a particular amount of characters:** Users can now trim or limit the length of content to a specified number of characters, helping to meet length requirements or constraints.
- **Integrated Search & Replace in the content of the tag feature:** This integration enables users to search for specific content within tags and replace it with alternative text, streamlining content management.
- **Added action chain process support:** This feature facilitates the creation of multiple actions for a single Feedzy magic tag. You can now add a tag for the import job and use multiple actions on it (_paraphrase, summarize, trim, etc._).

### **Improvements**
- Added feedback popup in the import screen

### **Bug Fixes**
- Fixed compatibility issue PHP 8.1+
- Fixed compatibility issue with WP version lower than 5.8
- Fixed categories feed URL sanitization issue

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishpanchal30 I'll post here the issues found regarding the release and will update the comment

- [ ] If i use only Feedzy free, add the [#item_content] tag and set it to be trimmed to 20 words, everything's fine. When i go back to edit the import, i can't open any settings and i have this error in the console https://vertis.d.pr/i/lSo2mY
- [ ] There is a console error visible on every feedzy tab https://vertis.d.pr/i/cmHfaS

**Comment by girishpanchal30** [comment]
@girishpanchal30 I've reviewed the bugs and fixed with this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/806

**Comment by girishpanchal30** [comment]
Hey @irinelenache,

> Deprecated notice on import page when using PHP 8.2 https://vertis.d.pr/i/mKJf0a

I believe this issue cannot be corrected by us. Due to this WP core error
Ref: https://core.trac.wordpress.org/ticket/57974

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30

- [ ] Found an issue related to the ChatGPT paraphrasing. Using [this feed](https://www.yahoo.com/news/rss/world/) and [this prompt](https://vertis.d.pr/i/c9GOA2) to import 3 items, i'm getting some strange results. Two of the items contain some random content, unrelated to the article https://vertis.d.pr/i/lr9YGK , https://vertis.d.pr/i/2rdPKK , and one of them just replaced the {content} in the prompt https://vertis.d.pr/i/n33OLn https://vertis.d.pr/i/LsZpXC (without any paraphrasing effect)

**Comment by girishpanchal30** [comment]
@irinelenache Due to the API context length limit it will return default content.

```
string(236) "{"code":"feedzy_openai_error","message":"This model's maximum context length is 4097 tokens, however you requested 6090 tokens (981 in your prompt; 5109 for the completion). Please reduce your prompt; or completion length.","data":null}"
```

We have two options for this issue:

1) Import with an error message
2) Display with {content} default textbox value

**Comment by vytisbulkevicius** [comment]
@girishpanchal30,

The context length limit here, do you mean that the original content of the feed is too long or the returned content from OpenAI after it's rephrased is too long?

**Comment by girishpanchal30** [comment]
> do you mean that the original content of the feed is too long

@vytisbulkevicius Yes, I think @irinelenache tested with the full_content magic tag. Otherwise, it works fine with item_content, item_desc

**Comment by vytisbulkevicius** [comment]
Also, even [#item_content] tag might exceed the limit in some feeds where content is longer in the feed itself

**Comment by girishpanchal30** [comment]
@vytisbulkevicius I've set a 3000 char limit as we have done before in translation and paraphrasing service.
Ref: https://github.com/Codeinwp/feedzy-full-post/blob/master/web/app/plugins/feedzy-api/classes/FeedzyFullPost/Admin/Admin.php#L672

Also, fixed this issue https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/589#issuecomment-1770416459

PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/809

**Comment by irinelenache** [comment]
@girishpanchal30 @vytisbulkevicius The ChatGPT issue is fixed now, it can be merged to development ✔️

**Comment by rodica-andronache** [comment]
@girishpanchal30 when Gutenberg is installed, there are some errors in the console and the survey pop-up is not working anymore https://vertis.d.pr/v/urYI7M
Also, unrelated to Gutenberg, there are some other errors in the console and the survey pop style looks broke, as can be seen in the recording. You can test it here
`https://ashamed-anaconda-i4p9e.vertisite.cloud/wp-admin
user: admin
pass: admin`

**Comment by girishpanchal30** [comment]
@rodica-andronache Fixed with this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/814

**Comment by rodica-andronache** [comment]
@girishpanchal30 thanks for the fixes, it's working well. Just the close button from the feeedback pop up looks a bit wrong when Gutenberg is installed. the color of the text is not visible https://vertis.d.pr/i/C2Buf8

**Comment by rodica-andronache** [comment]
@girishpanchal30 talked to Vytis and `Summarize with Feedzy`  should be changed to `Summarize with ChatGPT`. thank you! https://vertis.d.pr/i/tiZMXd

**Comment by girishpanchal30** [comment]
@rodica-andronache Fixed with latest the commit

**Comment by rodica-andronache** [comment]
@girishpanchal30 now the close button is not visible when Gutenberg is NOT installed https://vertis.d.pr/i/WPYr0v

**Comment by girishpanchal30** [comment]
@rodica-andronache Fixed, Please check with the latest commit.

**Pull request merged**
