### PR TITLE
Fixed scheduler time issue

### PR DESCRIPTION
**Pull request by girishpanchal30**
### Summary
Improve scheduler util class 

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/827

### CODE REVIEW

**Review by HardeepAsrani — APPROVED** [review]

**Comment by vytisbulkevicius** [comment]
@girishpanchal30 @HardeepAsrani,

I installed These PRs:
Pro: https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/809
Lite: https://github.com/Codeinwp/feedzy-rss-feeds/pull/1043

And manually aplied this fix from current PR.

The behavior changed that now I don't see import job next run time at all:
image

And running feedzy_cron Event:
image

Doesn't trigger the import jobs:
image


Does it work for you?

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius Can you check now?

**Comment by selul** [comment]
@girishpanchal30 @vytisbulkevicius @HardeepAsrani this has been fixed by me already here https://github.com/Codeinwp/feedzy-rss-feeds/pull/1037/commits/21e3b69045e44a784b23bdb80fd44e854526941b, which is on dev. 

Also this was not fixing the inconsistency with is_scheduled function @HardeepAsrani, the original method you developed is returning either true false or a timestamp based on the environment, it should return only false or a timestamp.

**Comment by girishpanchal30** [comment]
@selul @HardeepAsrani

> it should return only false or a timestamp.

The `get_next` method returns a timestamp if a scheduled job is found; otherwise, it returns `false`. Refer to the diff below for details.

```diff
 	public static function is_scheduled( string $hook, array $args = array() ) {
-		if ( function_exists( 'as_has_scheduled_action' ) ) {
-			return as_has_scheduled_action( $hook, $args );
-		}
-
-		if ( function_exists( 'as_next_scheduled_action' ) ) {
-			// For older versions of AS.
-			return as_next_scheduled_action( $hook, $args );
-		}
-
-		return wp_next_scheduled( $hook, $args );
+		return self::get_next( $hook, $args );
 	}

**Comment by selul** [comment]
yes, thats exactly what is_scheduled is doing atm in my fix.

**Comment by girishpanchal30** [comment]
@selul

I've checked with dev and it seems the incorrect time is being displayed.

image

With this PR, the correct time is displayed.

image

Should I update the `is_scheduled` method to use the `get_next` method?

**Comment by selul** [comment]
We dont need any next method, the is scheduled is enough.

**Comment by girishpanchal30** [comment]
@selul Okay, In this case, we don’t need to merge this PR. Please close this PR when you can.

**Pull request closed without merging**
