### PR TITLE
Improvement in AI API integration

### PR DESCRIPTION
**Pull request by girishpanchal30**
### Summary
More details here - https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/795#issue-2735579565

### Will affect visual aspect of the product
Yes

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/792

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Here I see the upsells for Pro are gone now that we've changed to Integrations page. We need to bring those previews back to give user an idea on what they get in the Pro version.

Do we want it back in the Settings for better visibility for upsells in Pro or an Integrations page with disabled sections.

@selul @vytisbulkevicius

**Review by HardeepAsrani — APPROVED** [review]
Good looks good, I've left a separate comment for lack of disabled sections for upsells and let's wait for the team to get back.

**Comment by vytisbulkevicius** [comment]
@HardeepAsrani, I recommend having them disabled in the Integrations page. Integrations menu item should be clickable and then we see all the sections disabled there as before it was in Settings:
image

**Comment by girishpanchal30** [comment]
@HardeepAsrani @vytisbulkevicius I’ve added the integration upsell sections and rebased the branch.

**Comment by vytisbulkevicius** [comment]
Looks good

**Comment by HardeepAsrani** [comment]
@girishpanchal30 Can you rebase with development fix the merge conflicts here? You just need to change the action-popup.js to index.js and it should be fine. I can do it myself but I'm not sure if you have any local changes that need to be comitted.

**Comment by girishpanchal30** [comment]
@HardeepAsrani Done!

**Pull request merged**
