### PR TITLE
Fixed set custom featured image issue

### LINKED ISSUE #755: Featured image is not assigned to imported posts if URL of image is used instead of [#item_image] tag
### Description

Starting with version 4.2.2 - https://github.com/Codeinwp/feedzy-rss-feeds/releases/tag/v4.2.2

Featured image is not imported for posts if you use URL for the featured image:
image
And a tag.

Also, user reported this happening with image assigned in Settings->General section where we can also assign image instead of taking it from the RSS XML Feed.

I assume this issue could be related to the solution that was used to fix "Multiple attachments generating issue".

Rolling back Free plugin to 4.2.1 version fixes the issue.

### Step-by-step reproduction instructions

1. Create an import and to import featured images use URL of image instead of [#item_image] or another tag.
2. Run the import and see that featured images are not imported for items.
3. Rollback to Feedzy free 4.2.1 and try again, image is there for imported posts as a featured image.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2203822310/364407

### Environment info

_No response_

### Is the issue you are reporting a regression

Yes, this is a regression.

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #755

### CODE REVIEW

**Comment by vytisbulkevicius** [comment]
Hey @girishpanchal30,

Here is a conflict that needs to be resolved, thanks

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Resolved

**Comment by vytisbulkevicius** [comment]
Thanks @girishpanchal30,

Should I force merging this too because of the same cypress test failure?
And same for the release itself https://github.com/Codeinwp/feedzy-rss-feeds/pull/757

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Checking, I'll try to replicate this in my local

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I've checked with local and it's working fine, can please force merge into development?
I'll check with development branch if generate same error.

Thanks

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Thanks, Checking the cypress issue with the development branch

**Pull request merged**
