### PR TITLE
Add second time validation for the XML namespace DC in XML source URL

### PR DESCRIPTION
**Pull request by girishkrishaweb**
Authors of the items are being ignored with some feeds - issue
To solve this we have added 2nd time validation in XML URL source.

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishkrishaweb @vytisbulkevicius i get this error https://prnt.sc/10o7sud when i try to activate the import job with this feed https://mediafeed.cheapism.com/mediafeed-articles.xml . 
Is it a problem from the provided feed or from the PR?

It worked fine with this feed from the issue https://www.theguardian.com/uk/rss and this feed that i found https://www.buzzfeed.com/world.xml

**Comment by vytisbulkevicius** [comment]
I'm not able to replicate this issue with https://mediafeed.cheapism.com/mediafeed-articles.xml feed - import job saves for me with this feed.

I've seen this error before with a valid feed and wasn't sure what could have caused it but this time it works fine for me: https://vertis.d.pr/LVApmn

**Comment by girishkrishaweb** [comment]
@irinelenache & @vytisbulkevicius After confirming with @selul I created the XML feed validation for the DC namespace but validation is working with the **Save** button only, We will check with the **Save & Activate**.

The DC namespace should be valid as per the requirement of the SimplePie library and there are some XML URLs where we are getting the wrong DC namespace URL and due to this, we are not able to import those feeds.

**Comment by girishkrishaweb** [comment]
@vytisbulkevicius Just want to know that have you applied the patch before testing this? I tested this issue many times but I did get a validation while saving the feed post. I have tried with both the button **Save** and **Save & Activate** 

Here is the demo video - https://www.loom.com/share/0aa5017578064f5a94567b9b9b4cc161

Also, I want to know the PHP, WP, and plugin versions where you tested this.

**Comment by irinelenache** [comment]
@girishkrishaweb I get the validation error both with **Save** and **Save & Activate**.  So the mentioned feed (https://mediafeed.cheapism.com/mediafeed-articles.xml) throwing that error is the expected behaviour?

**Comment by girishkrishaweb** [comment]
@irinelenache Yes, Here we have an issue with DC namespace. So we added validation for it. Thanks

**Pull request closed without merging**
