### PR TITLE
Improved remove duplicates

### PR DESCRIPTION
**Pull request by girishpanchal30**
### Summary
I have enhanced the duplicate removal process during import based on the suggestion provided here: https://github.com/Codeinwp/feedzy-rss-feeds/issues/1006#issuecomment-2540995371

### Will affect visual aspect of the product
Yes

### Screenshots
image

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/1006

### CODE REVIEW

**Review by selul — APPROVED** [review]

**Comment by selul** [comment]
@girishpanchal30 can you add some tests maybe for this? PHPUnit.

**Comment by girishpanchal30** [comment]
@selul Yes sure!

**Comment by girishpanchal30** [comment]
> @girishpanchal30 can you add some tests maybe for this? PHPUnit.

@selul Sorry, we can only write the test case in the Pro version as it includes a new field for Pro users.  
We can add PHPUnit later after releasing the Lite version.

**Comment by selul** [comment]
we can add now, let me know what solutions do you have.

**Comment by girishpanchal30** [comment]
@selul Ok, we can bypass the `feedzy_is_pro()` check during the import job by utilizing the `defined( 'TI_UNIT_TESTING' )` condition.  

For example:  
`( defined( 'TI_UNIT_TESTING' ) || feedzy_is_pro() ) && ! empty( $mark_duplicate_tag )`

**Comment by girishpanchal30** [comment]
@selul I've implemented PHPUnit test assertions to verify duplicate items and added e2e testing for upsell.

**Comment by girishpanchal30** [comment]
@selul I have implemented the mock function for the PHPUnit test case. Please review it and let me know if any changes are needed.

**Pull request merged**
