### PR TITLE
Added feedback popup in import screen

### LINKED ISSUE #774: Reusing Otter's Feedback Mechanism in Feedzy's Importing Editor
### What problem does this address?

We currently have an efficient feedback sharing system in Otter. A similar system can be utilized within Feedzy's importing editor interface. This will enable us to gain valuable insights from users, thereby enhancing our ability to make more user-centric improvements.

@vytisbulkevicius

@Codeinwp/design-team 

### What is your proposed solution?

_No response_

___
### [Figma](https://www.figma.com/file/vJ62MRf3FgOBd1i8WWJeIv/Feedzy?type=design&node-id=2212-4030&mode=design&t=AG3rr0MTDqGyEEsm-11)

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #774

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@girishpanchal30 After I finish taking the survey, there isn’t any way of closing the Thank you popup https://vertis.d.pr/i/J9hmra . Clicking outside of it does not do anything

**Comment by girishpanchal30** [comment]
@rodica-andronache Added a close button in the thank you popup, you can verify with the latest commit.

**Comment by rodica-andronache** [comment]
@girishpanchal30 everything's working well now with the interface 👍 I don't know where the feedback is actually stored to see if it actually gets there

**Comment by vytisbulkevicius** [comment]
Hey @girishpanchal30,

Can you please resolve this conflict?

**Comment by girishpanchal30** [comment]
@dependabot rebase

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Resolved

**Pull request merged**
