### PR TITLE
chore: add BF deal

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Add a Black Friday deal.

## Screen Shots

image

image

image

## Testing

1. Check if the banners appear with the correct link/URL. More about this here: https://github.com/Codeinwp/themeisle/issues/1575#issuecomment-1757321452
2. By using all three plugins (Neve, Otter, Feedzy), check the admin notice (the small one) priority. There should be notice only for the highest priority product. The order is Neve > Otter > Feedzy. More on this here: https://github.com/Codeinwp/themeisle/issues/1575#issuecomment-1761388729

The giant banners will have a dynamic text that shows the remaining time in the top-left corner. The start is set early to facilitate the test (it will be changed after the approval). The time interval set for testing is 2023-10-10 00:00:00 and 2023-11-27 23:59:00. If possible, try to change the server time to see if the banner is working correctly when the time is over.

The PRs are:
- Neve: https://github.com/Codeinwp/neve/pull/4121
- Otter: https://github.com/Codeinwp/otter-blocks/pull/1922
- Feedzy: https://github.com/Codeinwp/feedzy-rss-feeds/pull/805

### CODE REVIEW

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
One more issue, I found is that the notices appear even if you've Pro version installed. As mentioned in the issue, the notice shouldn't be visible if the user has Pro version.

And the Banner on other pages don't appear if you dismiss the global notice. Was this how Harshit requested or was a mistake?

**Comment by harshitarora-in** [comment]
@Soare-Robert-Daniel I can not see the LTD banner on the `Import posts` and `Feed categories` page.

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
The banner doesn't appear on non-Settings page anymore. Can you please confirm that all the plugins meet all the conditions that we had defined? With they're installed separately and when they're installed together.

**Review by HardeepAsrani — APPROVED** [review]

**Comment by Soare-Robert-Daniel** [comment]
Fixes in https://github.com/Codeinwp/feedzy-rss-feeds/pull/815

**Pull request merged**
