### PR TITLE
Added individual fallback image setting

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close Codeinwp/feedzy-rss-feeds-pro#570

### CODE REVIEW

**Comment by vytisbulkevicius** [comment]
Hey @girishpanchal30,

Can you please resolve this conflict?

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Resolved

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Can you please merge this PR into the development branch? After merging, I believe it will automatically resolve itself.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Ignore the above message, I've fixed it with the latest commit.

**Pull request merged**
