### PR TITLE
Fix undefined index for the error_empty

### PR DESCRIPTION
**Pull request by girishkrishaweb**
Tested in different PHP versions.

### CODE REVIEW

**Comment by irinelenache** [comment]
I tested this PR with Elementor feedzy widget, completed all options and got these errors in the log:
[debug.log](https://github.com/Codeinwp/feedzy-rss-feeds/files/6075702/debug.log)

**Comment by girishkrishaweb** [comment]
@irinelenache I checked the debug log and found there are multiple issues with the variables. I updated the code for it. Thanks

**Comment by irinelenache** [comment]
@girishkrishaweb i still get the same errors in the log, with the last version you updated.

**Comment by girishkrishaweb** [comment]
@irinelenache You should apply this PR #496 and PR #502 to verify the https://github.com/Codeinwp/feedzy-rss-feeds/issues/312 and https://github.com/Codeinwp/feedzy-rss-feeds/issues/474 issue. Thanks

**Comment by irinelenache** [comment]
@girishkrishaweb tested it with your indications and now it's fixed 👍

**Pull request closed without merging**
