### PR TITLE
Added Gutenberg Block for Feedzy

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Added Gutenberg block for Feedzy, as well as all the dependencies for it. It needs a lot of testing to make sure it's working everywhere, with free and pro.

Reviews and feedback are needed. @contactashish13 @selul

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@HardeepAsrani good job 👍 
what I tested so far:
- clicking on Edit as HTML makes the block empty https://prnt.sc/jctc4p
- not the entire feed is imported. Is that ok? shouldn't maybe be an option for this, if it's not the whole feed?
- I created a feedzy block and published it. After that, I duplicated the block and clicked Convert to Shared Block for the first block. At this point, trying to update the page is not working for me. It's giving some errors in the console, but I'm not sure if it's from gutenberg, or from feedzy.

**Comment by HardeepAsrani** [comment]
@rodica-andronache 

1. Because no HTML is there, so that's why. People aren't supposed to edit HTML as all of the data will be passed to a shortcode and that's how it will work.

2. The entire feed, as much as available, is being imported. You can select how many you want to have from the Inspector/Sidebar of the block. By default, only 5 items appear.

3. I'll check the third one and see.

**Comment by HardeepAsrani** [comment]
Can you give a video of third one? Works fine for me.

**Comment by HardeepAsrani** [comment]
@rodica-andronache in: https://github.com/Codeinwp/feedzy-rss-feeds/pull/127/commits/19d2c0a86c8380a157e173d38fc41c8fc9903d21, I disabled support for "Edit as HTML" so the button won't appear at all now.

**Comment by rodica-andronache** [comment]
@HardeepAsrani thanks. I tried replicating that problem again, but I wasn't able to do it. I guess it was something with my instance. 
I had another round of testing, and for me, everything is ok, except the dropdown options. this is how it appears to me in both firefox and chrome https://prnt.sc/jd5fyv. 

@rohittm would you have time to do a round of testing here 👍  Let me know

**Comment by HardeepAsrani** [comment]
@rodica-andronache Seems like default Gutenberg styles. Works fine for me but I’ll chrck. Also, did you test feed categories?

**Comment by rohittm** [comment]
@HardeepAsrani The block seemed to work fine. There's one thing I tested:
when I switch to classic editor, I added feedzy shortcode, and clicked on "Update", Switching back to Gutenberg, removes the block.

**Comment by rodica-andronache** [comment]
@rohittm I'm not sure if it's Gutenberg or the block, but sometimes is working for me, sometimes no. sometimes I get a js error when trying to update the page. For example, I tried now on my home laptop with this feed https://feed.zazzle.com/rss?qs=clothes and it's not working at all. is not showing any content for my post, unless I delete the block.
this option seems to work a bit crazy https://prnt.sc/jion10.

I would like you to do a deeper testing, with more cases, and all the options, and a report on it, so we can be sure everything is ok.
Thanks 👍

**Comment by HardeepAsrani** [comment]
I've done very deep testing with hundreds of test cases and it worked just fine. It's possible that Gutenberg changed or there was some type of content in the feed which the block wasn't able to handle. It's a big mess to work with Gutenberg. :D

Maybe ask few people to somehow try to break the block so we could find bugs in it?

**Comment by rodica-andronache** [comment]
Let's first see the report from Rohit :D

**Comment by selul** [comment]
Regarding the codebase, in my point of view, it has a GO. Well done @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@rodica-andronache @contactashish13 The Block is giving an error (check for the AJAX requests' response) which is because of this PR: https://github.com/Codeinwp/feedzy-rss-feeds-pro/commit/816cead3969ce3f1c98feed5ccd356bf4d2549eb

```
https://github.com/Codeinwp/feedzy-rss-feeds-pro/commit/816cead3969ce3f1c98feed5ccd356bf4d2549eb
```

It happens with Pro version only.

**Comment by HardeepAsrani** [comment]
@contactashish13 Don't forget about this. 😄

**Comment by contactashish13** [comment]
@HardeepAsrani I don't get this. The error says line 1475 but the class has only 1385 lines. Can you mention the steps to reproduce this?

**Comment by rodica-andronache** [comment]
@contactashish13 I think is about this https://github.com/Codeinwp/feedzy-rss-feeds-pro/blob/development/includes/admin/feedzy-rss-feeds-pro-admin.php#L1475 in the PRO version

**Comment by contactashish13** [comment]
@HardeepAsrani can you add this snippet and commit so that its part of the same PR?

```
	private function fetch_additional_content( $itemArray, $item ) {
		$url	= $item['item_url'];
		if ( empty( $url ) && array_key_exists( 'item_url', $itemArray ) ) {
			$url    = $itemArray['item_url'];
		}
		if ( empty( $url ) ) {
			return $itemArray;
		}

		$host   = parse_url( $url, PHP_URL_HOST );
```

**Comment by rodica-andronache** [comment]
@contactashish13 you can add the code here https://github.com/Codeinwp/feedzy-rss-feeds/pull/125 and check if everything is ok, thank you 💯

**Comment by contactashish13** [comment]
@rodica-andronache this change in pro. Which PR should this be part of?

**Comment by rodica-andronache** [comment]
@contactashish13 sorry, here https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/98 :D

**Comment by contactashish13** [comment]
@rodica-andronache done

**Comment by HardeepAsrani** [comment]
Not a good day to merge, it was. :)

Gutenberg updated and changed a lot of things (mostly they just moved Components from one library to another), and I've to fix them so, just wait! 😆 @rodica-andronache

**Pull request merged**
