### PR TITLE
feat: add regex support to Search/Replace action

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### Summary

This PR adds support for Regular expression support to Search/Replace feature.

### Will affect visual aspect of the product

No

### Test instructions

- Make sure the Search replace works like it was doing previously when used with simple strings.
- When used with a Regular expression, it should properly detect and replace the strings. You can use ChatGPT to generate and https://regex101.com/ to test Regex.

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/627.

### CODE REVIEW

**Review by Soare-Robert-Daniel — APPROVED** [review]

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius You will need to escape your regex to look like this: `/\band\b/` as it thinks you're looking for `\band\b` string not regex. Let me know if that works.

**Comment by selul** [comment]
@vytisbulkevicius or I think you can use *band*

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius Just to avoid the confusion, Marius meant `*and*` 😄 Your initial regex visually looks like it's trying to capture `band`

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius what do you mean? I'm confused by the second sentence. 😀

**Comment by vytisbulkevicius** [comment]
Discussed this on Slack with Hardeep :D

**Pull request merged**
