### PR TITLE
Add ability to use external images

### PR DESCRIPTION
**Pull request by girishkrishaweb**
Tested with PHP7.4, 7.3, 7.2, 7.1

### CODE REVIEW

**Comment by irinelenache** [comment]
Tested with this feed https://rss.app/feeds/xJRj9yVAzpPVBZrV.xml
This is how the post looks in front-end (duplicated images):
https://user-images.githubusercontent.com/67897586/109811326-58355a80-7c33-11eb-8ae5-dda329d3af28.png

This is how the post looks in editor: https://prnt.sc/10c508f

No images saved in media library, the duplicated images use external links.

@selul you know if this should be the expected behaviour?

**Comment by selul** [comment]
the images should not be duplicated but indeed the image links should be external. You can read more about the expected behavior here https://github.com/Codeinwp/feedzy-rss-feeds/issues/492

**Comment by irinelenache** [comment]
@girishkrishaweb any changes for this? https://github.com/Codeinwp/feedzy-rss-feeds/pull/498#issuecomment-789711214

**Comment by girishkrishaweb** [comment]
@irinelenache You were getting 2 images because the first image came from an External feature Image(Thumbnail) and the second one came from post content or I would say it came from an item description of your XML feed. - We have added a checkbox in the backend of the plugin's feed setting where you can select the way how to use the feature image. - https://drive.google.com/file/d/1pldRF11VXYzdGdkDWU7rAIuNyolE2KYh/view

I mean to say you would able to select the internal and external path for the feature image while importing XML feed but with the external image, you won't get the attached feature image with feature media.

**Comment by irinelenache** [comment]
@girishkrishaweb thanks for explaining it 🙏  this PR works fine 👍

**Pull request closed without merging**
