### PR TITLE
Fix import custom value when using #item_full_content shortcode

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close Codeinwp/feedzy-rss-feeds-pro#398

### CODE REVIEW

**Comment by girishkrishaweb** [comment]
###How to test###

1. Create a new import using https://www.gq.com/feed/rss feed
2. Use [#item_full_content] in the Content field
3. Try to also add any custom tag to retrieve value (like [#item_custom_link], [#item_custom_category], etc.)

**Comment by irinelenache** [comment]
@girishkrishaweb i tried testing it with these feeds: https://www.gq.com/feed/rss , buzzfeed.com/world.xml
In the custom fields area, more than one value is extracted ( https://vertis.d.pr/t5wkog )
You can check it here: 
```
 Admin area URL: https://thinflag.tastewp.com/wp-admin 
 Username: irinel 
 Password: IXMd2AZJKi0 
```

**Comment by girishkrishaweb** [comment]
@irinelenache It seems like the code is not up-to-date.

You have to follow these branches on both the server.

The free version should have bugfix/398 branch code  
The pro version should have development branch code


image_2021_07_01T11_33_14_005Z

**Comment by irinelenache** [comment]
@girishkrishaweb Thanks for the input, tested again and it works fine with this feed https://www.gq.com/feed/rss
With this one, https://www.buzzfeed.com/world.xml , some items don't have the correct Link imported https://vertis.d.pr/ZESpN4

**Comment by girishkrishaweb** [comment]
@irinelenache As per the SimplePie XML library, We need an XML feed URL with either ascending order or Descending order to verify with feedzy-full-content (To verifying our host). But in this URL https://www.buzzfeed.com/world.xml  seems to be different. The ordering is not acceptable to get the full content of the feed.

The index of feed is different when we get from feedzy-full-content plugin host.

Cc: @selul

**Comment by irinelenache** [comment]
@girishkrishaweb With https://github.com/Codeinwp/feedzy-full-post/pull/17 merged, tested with this Feedzy lite PR and release version of Feedzy pro and the issue seems to be fixed 👍

**Pull request merged**
