### PR TITLE
fix: allow agency lifetime ltd

### PR DESCRIPTION
**Pull request by preda-bogdan**
### Summary

Allow Agency Lifetime LTD plan features.

Closes: Codeinwp/themeisle#1599

### CODE REVIEW

**Comment by selul** [comment]
@preda-bogdan this should be fixable from the API endpoint aswell, to map the price id?

**Comment by selul** [comment]
@preda-bogdan yes, and we can map the new price id to some one that is already checked in the plugin, to avoid making another release.

**Comment by preda-bogdan** [comment]
@selul ok, it makes sense, I can do the remapping inside the store.

**Comment by preda-bogdan** [comment]
Closing this in favour of Codeinwp/store-themeisle/pull/598

**Pull request closed without merging**
