### PR TITLE
Enclosures that do no specify image extension are not imported even if type is image/jpeg

### PR DESCRIPTION
**Pull request by contactashish13**
#472

### CODE REVIEW

**Comment by irinelenache** [comment]
@contactashish13 when i downloaded your **test_rss.txt** file with **.xml** extension, opening it gives this error -> https://prnt.sc/uzs4kn . 
I tried to run the import both with your **test_rss.xml** file and with **cmgrss.xml** that i found on the support link provided (when i saved cmgrss.txt as xml it looked like this -> https://prnt.sc/uzs7up ), but i got `Nothing imported` notice both times -> https://prnt.sc/uzs90t . 
I used the **local path** for the feed source as you can see in the last picture ( file:///C:/Users/40785/Desktop/cmgrss.xml ). 
Let me know if i did something wrong or if i have to test it some other way.

**Comment by contactashish13** [comment]
@irinelenache the path should be a URL, whether local or external

**Comment by contactashish13** [comment]
@rodica-andronache this is getting stale for almost 2 months. we should discard them or release them.

**Comment by rodica-andronache** [comment]
@contactashish13 can't figure out how to test this. I've tried to upload the .XML file to drive, and create a shareable link from there to use in the import, but nothing is imported.
Can you please help with this, so we can test it? Thanks

**Comment by contactashish13** [comment]
@rodica-andronache I tested by creating this XML in the wp-content folder and then using that URL. Doesn't that work for you?

**Comment by rodica-andronache** [comment]
@contactashish13 it doesn't work for me. Is there something I'm doing wrong? https://www.loom.com/share/03e5ac7f5b424031902a0c8d3e0a2751

**Comment by contactashish13** [comment]
@rodica-andronache it needs to be a valid http/https URL

**Comment by rodica-andronache** [comment]
@contactashish13 ok, thanks, I've managed to test it, by using the http://localhost:10028/wp-content/cmgrss.xml link, and it's working well.
Could you please bring in the changes from development in this PR too, so we can see if it's working well with the latest changes before merging it?

**Comment by contactashish13** [comment]
@rodica-andronache done

**Pull request merged**
