### PR TITLE
Apply existing patch for the tags retrieve content of random item

### PR DESCRIPTION
**Pull request by girishkrishaweb**
Issue - https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/370

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishkrishaweb @vytisbulkevicius 
I tested this and it works fine with these feeds:

- https://feeds.groupninemedia.com/feeds/nowthis/aol (from the issue) and tag  [#item_custom_media:content@url]
- https://www.buzzfeed.com/world.xml (not present in the issue) and tag [#item_custom_media:thumbnail@url]

It doesn't work with this feed provided in the issue:
https://www.theguardian.com/uk/rss and tag [#item_custom_media:content@url] . This provides random URL's from other items. I don't know if this happens because every item has 2 media:content tags, with different widths ( https://prnt.sc/10oahaz ).

@tudor-themeisle can you confirm this behaviour?

**Comment by girishkrishaweb** [comment]
@irinelenache Yeah, the same behavior on our side as well. For this, we have fixed this behavior by update the code. You can test now but make sure the patch should be applied: https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/370

**Comment by irinelenache** [comment]
@girishkrishaweb Tested again and for this feed that had problems ( https://www.theguardian.com/uk/rss ) now it gets both links, but they are not clickable or used with `img tag` like in the other feeds. This is how the posts look https://prnt.sc/10v8q8v . Can this be changed or this is the expected behaviour?

**Comment by girishkrishaweb** [comment]
@irinelenache The links are part of the content, so we should extract them as plain text only.

**Pull request closed without merging**
